window.COMMUNITY = {
  ICON: "assets/community/icons/",
  AVATAR: "assets/community/avatars/",
  IMAGE: "assets/community/images/",

  cohorts: [
    {
      id: "pmp-general",
      section: "general",
      title: "PMP General Cohort",
      subtitle: "All PMP Learners",
      liveSessions: 1,
      unread: 30,
      onlineExtra: 13,
      members: 124,
      avatarStack: ["stack-1.jpg", "stack-2.jpg", "stack-3.jpg", "stack-4.jpg", "stack-5.jpg"],
      membersCount: 22,
      onlineCount: 4,
    },
    {
      id: "march-exam",
      section: "exam-month",
      title: "March Exam Cohort",
      subtitle: "All March 2026 Exam Learners",
      liveSessions: 0,
      unread: 30,
      onlineExtra: 13,
      members: 124,
      avatarStack: ["stack-1.jpg", "stack-2.jpg", "stack-3.jpg", "stack-4.jpg", "stack-5.jpg"],
      membersCount: 22,
      onlineCount: 4,
    },
  ],

  noteDismissKey: "cs-community-note-dismissed",
  partnersMatchKey: "cs-community-partners-matched",

  partners: {
    partner: {
      name: "Patrick Adanini",
      avatar: "match-partner.jpg",
      avatarYou: "match-you.jpg",
      description:
        "A consistent learner with a strong exam readiness score, steady sprint velocity, and an active streak—reliable, disciplined, and an ideal accountability partner.",
    },
    leaderboard: [
      { rank: "gold", name: "Patrick Adanini (You)", avatar: "patrick.jpg", streak: "23 days", progress: "50%", readiness: "50%", isYou: true },
      { rank: "silver", name: "Patrick Adanini", avatar: "patrick.jpg", streak: "23 days", progress: "50%", readiness: "50%" },
      { rank: "silver", name: "Patrick Adanini", avatar: "patrick.jpg", streak: "23 days", progress: "50%", readiness: "50%" },
      { rank: "4th", name: "Patrick Adanini", avatar: "patrick.jpg", streak: "23 days", progress: "50%", readiness: "50%" },
    ],
    achievements: [
      {
        id: "ach-risk-guru",
        month: "September 2025",
        author: "Patrick Adanini (You)",
        avatar: "patrick.jpg",
        badge: "award-risk-guru.svg",
        title: "Risk Guru",
        subtitle: "100% Accuracy in Risk Mgmt",
        reactions: ["👍", "💡"],
        reactionCount: 3,
        commentCount: 5,
      },
      {
        id: "ach-domain-master",
        month: "September 2025",
        author: "Michael Adeyemi",
        avatar: "leo.jpg",
        badge: "award-domain-master.svg",
        title: "Domain Master x5",
        subtitle: "Master each PMP domain",
        reactions: ["👍", "💡"],
        reactionCount: 3,
        commentCount: 5,
      },
    ],
    reactions: [
      { name: "Patrick Adanini (You)", avatar: "patrick.jpg", emoji: "👍" },
      { name: "Michael Adeyemi", avatar: "leo.jpg", emoji: "👍" },
      { name: "Robin Counts", avatar: "session-listener-4.jpg", emoji: "💡" },
    ],
    comments: [
      {
        id: "pc1",
        author: "Michael Adeyemi",
        avatar: "leo.jpg",
        text: "Rewatch this introductory PMP video before starting the application process.",
        reactions: 4,
        replies: 12,
      },
      {
        id: "pc2",
        author: "Patrick Adanini (You)",
        avatar: "patrick.jpg",
        text: "Great milestone — keep the streak going!",
        reactions: 2,
        replies: 0,
      },
    ],
  },

  messages: [
    {
      id: "ai-welcome",
      type: "ai",
      sender: "CertSprint AI",
      time: "2:09PM",
      text:
        "Welcome to the PMP General cohort! 🎉 This is the community for ALL PMP learners on the platform. Share tips, ask questions, and support each other.",
    },
    {
      id: "m1",
      type: "incoming",
      sender: "Leo Culhane",
      avatar: "leo.jpg",
      time: "2:09PM",
      text:
        "Hey everyone! Just finished Sprint 3's Earned Value section. Anyone else struggling with EAC calculations?",
      reactions: [
        { emoji: "👍", count: 3, active: true },
        { emoji: "💡", count: 1, active: false },
      ],
      optionsType: "text",
    },
    {
      id: "m2",
      type: "incoming",
      sender: "Cristofer Calzoni",
      avatar: "cristofer.jpg",
      time: "2:09PM",
      text: "I think i like the way the you all express yourself and are commited to work",
      image: "chat-attachment.jpg",
      optionsType: "image",
    },
    {
      id: "m3",
      type: "incoming",
      sender: "Cristofer Calzoni",
      avatar: "cristofer.jpg",
      time: "2:09PM",
      imageOnly: "chat-attachment.jpg",
      optionsType: "image",
    },
    {
      id: "m4",
      type: "incoming",
      sender: "Cooper Rosser",
      avatar: "cooper.jpg",
      time: "2:09PM",
      text: "I think i like the way the you all express yourself and are commited to work",
      optionsType: "text",
    },
    {
      id: "m5",
      type: "outgoing",
      sender: "You",
      avatar: "you.jpg",
      time: "2:09PM",
      text: "I think i like the way the you all express yourself and are commited to work",
      status: "sent",
    },
    {
      id: "m6",
      type: "outgoing",
      sender: "You",
      avatar: "you.jpg",
      time: "2:09PM",
      text: "I think i like the way the you all express yourself and are commited to work",
      status: "pending",
    },
  ],

  emojiQuick: ["😂", "👍", "💡", "🎉"],
  emojiGrid: [
    "😀", "😁", "😂", "🤣", "😊", "😍", "🥳", "👍",
    "👏", "💡", "🔥", "✅", "❤️", "🙏", "💪", "🎯",
  ],

  reportReasons: [
    "Spam or misleading",
    "Harassment or hate speech",
    "Inappropriate content",
    "Off-topic",
    "Other",
  ],

  sessionDurations: ["15 mins", "30 mins", "45 mins", "60 mins", "90 mins"],

  sessions: {
    live: [
      {
        id: "live-risk",
        dayLabel: "Mon",
        dayNum: "09",
        title: "Risk Management Masterclass 🎯",
        description:
          "Walk through qualitative & quantitative risk analysis techniques with real exam scenarios.",
        host: "Paul Walker",
        timeStart: "12:00PM",
        timeEnd: "03:00PM",
        listening: 23,
        listenerAvatars: [
          "session-listener-1.jpg",
          "session-listener-2.jpg",
          "session-listener-3.jpg",
          "session-listener-4.jpg",
          "session-listener-5.jpg",
        ],
      },
    ],
    upcoming: [
      {
        id: "up-strategy",
        status: "pending",
        dayLabel: "Mon",
        dayNum: "09",
        title: "PMP Exam Strategy & Time Management",
        description:
          "Tips on how to pace yourself through 180 questions. Sharing what worked for recent passers.",
        host: "Darren Fletcher (You)",
        timeStart: "12:00PM",
        timeEnd: "03:00PM",
        isOwner: true,
      },
      {
        id: "up-approved",
        status: "approved",
        dayLabel: "Wed",
        dayNum: "11",
        title: "Agile Mindset Deep Dive",
        description: "Exploring hybrid approaches and when to apply predictive vs agile methods.",
        host: "Sarah Chen",
        timeStart: "10:00AM",
        timeEnd: "11:30AM",
        isOwner: false,
      },
    ],
  },

  ongoingSession: {
    id: "live-risk",
    title: "Risk Management Masterclass 🎯",
    host: "Marie Slacer",
    timeStart: "12:00PM",
    timeEnd: "03:00PM",
    description:
      "Walk through qualitative & quantitative risk analysis techniques with real exam scenarios.",
    speakers: [
      { name: "Marie Slacer", role: "Host", avatar: "session-listener-1.jpg", micOn: true },
      { name: "Eleanor Brix", role: "Speaker", avatar: "session-listener-2.jpg", micOn: false },
    ],
    listeners: [
      { name: "Marie Slacer", avatar: "session-listener-1.jpg" },
      { name: "Eleanor Brix", avatar: "session-listener-2.jpg" },
      { name: "Paul Walker", avatar: "session-listener-3.jpg" },
      { name: "Leo Culhane", avatar: "session-listener-4.jpg" },
      { name: "Sarah Chen", avatar: "session-listener-5.jpg" },
      { name: "Cooper Rosser", avatar: "session-listener-1.jpg" },
      { name: "Cristofer Calzoni", avatar: "session-listener-2.jpg" },
      { name: "Darren Fletcher", avatar: "session-listener-3.jpg" },
      { name: "Robin Counts", avatar: "session-listener-4.jpg" },
      { name: "MJ Price", avatar: "session-listener-5.jpg" },
      { name: "Beth Davies", avatar: "session-listener-1.jpg" },
      { name: "Reta Taylor", avatar: "session-listener-2.jpg" },
    ],
    listenerTotal: 124,
    listening: 144,
    comments: [
      {
        id: "c1",
        sender: "Leo Culhane",
        avatar: "leo.jpg",
        time: "12:14PM",
        text: "Great explanation on EMV calculations!",
      },
      {
        id: "c2",
        sender: "You",
        avatar: "you.jpg",
        time: "12:16PM",
        text: "Can we go over contingency reserve vs management reserve again?",
        isOwner: true,
      },
    ],
    speakerRequests: [
      { id: "sr1", name: "Paul Walker", avatar: "session-listener-3.jpg" },
      { id: "sr2", name: "Sarah Chen", avatar: "session-listener-5.jpg" },
    ],
  },

  members: [
    { id: "m-you", name: "Darren Fletcher", avatar: "you.jpg", role: "Learner", online: true, isYou: true },
    { id: "m-leo", name: "Leo Culhane", avatar: "leo.jpg", role: "Learner", online: true },
    { id: "m-paul", name: "Paul Walker", avatar: "session-listener-3.jpg", role: "Host", online: true },
    { id: "m-sarah", name: "Sarah Chen", avatar: "session-listener-5.jpg", role: "Learner", online: false },
    { id: "m-cooper", name: "Cooper Rosser", avatar: "cooper.jpg", role: "Learner", online: true },
    { id: "m-cristofer", name: "Cristofer Calzoni", avatar: "cristofer.jpg", role: "Learner", online: false },
    { id: "m-marie", name: "Marie Slacer", avatar: "session-listener-1.jpg", role: "Moderator", online: true },
    { id: "m-eleanor", name: "Eleanor Brix", avatar: "session-listener-2.jpg", role: "Learner", online: true },
  ],
};
