(function(){
"use strict";
var stage=document.getElementById("cc-stage"),current=0,selected=null,answers=[];
var questions=[
 {anchor:"01",question:"What is the core distinction Alex Smith makes between 'delivery' and 'change'?",correct:1,options:["Delivery is faster and cheaper than change","Delivery describes what is built; change describes what the organization must do differently","Delivery focuses on people; change focuses on systems","They are synonymous terms in project management"],why:"Delivery refers strictly to the outputs or tools created by a project. Change is the human transition—how people adjust their behaviors to actually use those tools for value."},
 {anchor:"02",question:"According to the ACMP Standard, what is the purpose of 'Define the Change'?",correct:2,options:["To create a project plan with deliverables and go-live dates","To train staff on how to use new tools","To discern and specify the change the organization intends to adopt to meet a strategic objective","To identify the project's technical sponsor"],why:"In the CCMP mindset, defining the change isn't about scheduling; it's about identifying the specific shift required to meet high-level business goals."},
 {anchor:"03",question:"Which statement best describes a complete Change Definition?",correct:0,options:["A list of system features, training schedules, and go-live dates","A description of the behavioral and organizational transition required to realize strategic value","A high-level communication plan for all impacted stakeholders","A summary of the project budget and resource allocation"],why:"A complete definition must include the 'future state' of behaviors. Without the human transition element, the definition remains a technical output list."}
];
function icon(file,name){return '<span class="cc-icon-slot"><img class="cc-glyph cc-glyph--'+name+'" src="assets/icons/'+file+'" alt=""></span>'}
function nav(){return '<div class="cc-sb"></div><nav class="cc-nav"><button class="cc-nav-btn" data-action="back" aria-label="Back"><img src="assets/icons/arrow-left-02.svg" alt=""></button><p>COMPREHENSION CHECK</p><button class="cc-nav-btn cc-help" data-action="help" aria-label="Help"><img src="assets/icons/help-circle-24.svg" alt=""></button></nav>'}
function btn(text,action,cls){return '<button class="cc-btn '+(cls||"")+'" data-action="'+action+'">'+text+'</button>'}
function shell(body,foot){stage.innerHTML='<section class="cc-screen">'+nav()+body+(foot?'<footer class="cc-bnb">'+foot+'</footer>':'')+'</section>';bind()}
function intro(){current=0;selected=null;answers=[];shell('<div class="cc-intro"><header class="cc-intro-head"><span class="cc-badge">RECALL CHECK</span><h1>READY TO<br><em>REINFORCE?</em></h1><p>Test your initial recall of the lesson video before<br>moving to flashcard reinforcement.</p></header><img class="cc-art" src="assets/comprehension-check/recall-check.png" alt=""><div class="cc-stats"><article>'+icon("check-list-16.svg","check-list")+'<div><span>ITEMS</span><strong>3 Qs</strong></div></article><article class="time">'+icon("clock-01-16.svg","clock")+'<div><span>EST TIME</span><strong>60s</strong></div></article></div></div>',btn('Initialize Check '+icon("arrow-right-02.svg","arrow-right"),"start"))}
function question(){selected=null;var q=questions[current],letters=["A.","B.","C.","D."];var opts=q.options.map(function(text,i){return '<button class="cc-option" data-action="select" data-index="'+i+'"><i></i><span>'+letters[i]+'</span><p>'+text+'</p></button>'}).join("");shell('<div class="cc-recall-head"><span class="cc-badge">RECALL CHECK</span><h1>Lets see what you remember</h1><p>Answer from memory before proceeding</p></div><section class="cc-panel"><div class="cc-question-top"><span>RECALL ANCHOR '+q.anchor+'</span><b>PROGRESS <em>'+(current+1)+'/10</em></b></div><h2>'+q.question+'</h2><h3>SELECT YOUR RESPONSE</h3><div class="cc-options">'+opts+'</div></section>','<p class="cc-foot-note">SELECT AN ANSWER TO CONTINUE,</p>')}
function feedback(){var q=questions[current],correct=selected===q.correct,letter=String.fromCharCode(65+q.correct);var header=correct?'<div class="cc-result good">'+icon("checkmark-circle-02-16.svg","check")+'<strong>CORRECT LOGIC</strong><p>Correct answer is '+letter+'</p></div>':'<div class="cc-result wrong">'+icon("information-diamond-20.svg","diamond")+'<strong>Wrong Answer</strong><p>Correct answer is '+letter+'</p></div>';stage.insertAdjacentHTML("beforeend",'<div class="cc-overlay" aria-hidden="false"></div><section class="cc-sheet" aria-hidden="false"><div class="cc-handle"></div><div class="cc-sheet-content">'+header+'<article class="cc-why"><strong>Here’s why:</strong><p>'+q.why+'</p></article><div class="cc-sheet-actions">'+btn(icon("thumbs-up-20.svg","thumbs")+'Ok, got it',"next")+btn(icon("ai-brain-03-20.svg","brain")+'Brainstorm with AI',"brainstorm","ai")+'</div></div></section>');bind()}
function select(el){selected=Number(el.dataset.index);stage.querySelectorAll(".cc-option").forEach(function(o){o.classList.toggle("selected",o===el)});setTimeout(feedback,140)}
function next(){answers.push(selected);if(current<questions.length-1){current++;question()}else location.href=new URL('lms/active-recall.html', document.baseURI).href}
function bind(){stage.querySelectorAll("[data-action]").forEach(function(el){el.onclick=function(){var a=el.dataset.action;if(a==="back"){if(current||stage.querySelector(".cc-panel"))intro();else history.back()}else if(a==="help")location.href="support/help-support.html?from=comprehension-check";else if(a==="start")question();else if(a==="select")select(el);else if(a==="next")next();else if(a==="brainstorm")next()}})}
var demo=new URLSearchParams(location.search).get("view");if(demo==="q1"){current=0;question()}else if(demo==="q1-correct"){current=0;question();selected=1;feedback()}else if(demo==="q2"){current=1;question()}else if(demo==="q2-correct"){current=1;question();selected=2;feedback()}else if(demo==="q3"){current=2;question()}else if(demo==="q3-wrong"){current=2;question();selected=1;feedback()}else intro();
})();
