(function(){
"use strict";
var stage=document.getElementById("ct-stage"),page=0,params=new URLSearchParams(location.search);
var assetRoot="assets/core-terms/";
var terms=[
["Change","The transition from a current state to a future state - ACMP",["Change is not the tool, system, policy, or announcement.","Change is the movement between two states of reality.","It includes uncertainty, learning, disruption, and adjustment.","It unfolds over time and affects people differently."],"Many exam traps confuse change with implementation. If nothing actually transitions, no change has occurred."],
["Current State","The condition at the time the change is initiated - ACMP.",["How people actually work today, not how leadership thinks they work.","Not what policies say, not what process maps claim.","Includes habits, informal workarounds, cultural norms, existing beliefs.","Includes rewarded behaviours and trusted tools."],"Change efforts fail when the current state is assumed instead of assessed. Ignoring it creates resistance later."],
["Future State","The condition at the time when the benefits have been realized - ACMP",["The future state is not when the project ends.","It exists only when people consistently behave differently.","New ways of working are normal.","Benefits are actually realized."],"“Go-live” does not equal future state. Adoption plus benefit realization equals future state."],
["Adoption","Choosing to accept and demonstrate a new way of thinking or behaving. Adoption occurs when stakeholder behavior is consistent with the future state behavior. - ACMP",["Adoption is behavioral, not informational.","Training completed does not equal adoption.","Communication sent does not equal adoption.","Adoption occurs only when people choose to work differently.","New behaviors are sustained without enforcement."],"CCMP questions often describe busy change activity with low adoption. Always ask: Has behavior actually changed?"],
["Benefit","The quantitative and qualitative, measurable and non-measurable outcomes resulting from a change - ACMP",["Benefits are why the change exists.","Benefits answer the question: “So what?”","Can be financial, operational, experiential, or strategic."],"Activities are not benefits. Outputs are not benefits. Outcomes are benefits."],
["Benefit Realization","The achievement of the expected outcomes of a change - ACMP",["Benefit realization asks: Did the change deliver its promised value?","It requires adoption, sustained behavior change, and measurement over time."],"Sponsors are accountable for benefit realization, not change practitioners."],
["Change Impact","How people, process, technology, and the workplace are affected during the transition from the current state to the future state - ACMP",["Who is affected? How deeply? In what way?","Includes role changes, skill gaps, and workload shifts.","Includes emotional reactions and workplace adjustments."],"Change impact is diagnostic, not emotional. Without impact analysis, resistance is misdiagnosed."],
["Change Management","The practice of applying a structured approach to the transition of an organization from a current state to a future state to achieve expected benefits - ACMP",["Prepares people, supports transition, and enables adoption.","Integrates leadership alignment, stakeholder engagement, and readiness.","Includes communication, training, and reinforcement."],"Change management focuses on people adoption, not delivery."],
["Change Risk","An event or condition that, if it occurs, may have an effect on the change benefits - ACMP",["Change risks threaten not just delivery but adoption and sustainability.","Examples include sponsor disengagement, change fatigue, skill gaps, and cultural resistance."],"CCMP distinguishes change risk from project risk."],
["Change Saturation","When the amount of change occurring in an organization is more than can be effectively handled by those affected by the change - ACMP",["Saturation is about human capacity, not effort.","Symptoms include burnout, disengagement, and resistance.","Good changes fail when priorities conflict or recovery time is ignored."],"Resistance can be a symptom of saturation, not unwillingness."],
["Competency","The organizational or individual collection of knowledge, skills, and abilities - ACMP.",["Can people actually perform in the future state?","Includes technical skills, behavioral skills, mindset, and confidence.","Competency is being able to do it under pressure, consistently."],"At NovaCare: staff must be competent in both system use and new workflows."],
["Engagement","Stakeholder involvement and influence in the change process - ACMP",["Engagement is active participation, not passive awareness.","Engaged stakeholders influence outcomes, provide feedback, and advocate for change."],"Engagement is a leading indicator of adoption."],
["Governance","Decision-making processes, applied by authorized individuals or teams, for approving, monitoring, and adjusting change management activities - ACMP",["Ensures accountability, escalation paths, and disciplined decision-making.","Answers who decides, based on what information, and how course corrections happen.","Without governance, change drifts."],"Governance ensures disciplined decision-making. Without it, change drifts."],
["Outcome","A specific, measurable result or effect of an action or situation - ACMP",["Outcomes are observable results, not intentions.","“90% system usage” is an outcome.","“Improved communication” is not."],"Outcomes are observable results, not intentions."],
["Readiness","Preparedness to accept, effectively handle, and integrate impending change - ACMP",["Are we prepared to change now?","Includes willingness, capability, leadership support, and capacity.","Readiness is about capacity and confidence, not agreement."],"People may support a change but still be unready."],
["Resistance","A stakeholder’s opposition to a change - ACMP",["Resistance is information, not failure.","Signals fear of loss, lack of trust, unmet needs, or overload.","Resistance management addresses opposition through listening, adapting, and supporting."],"Suppressing resistance increases it."],
["Sponsor","The individual or group accountable for benefits realization - ACMP",["Authorizes change, provides visibility, removes obstacles, and reinforces importance.","Sponsorship aligns stakeholders to support and own a change.","Sponsorship is active, not symbolic."],"The Sponsor is accountable for benefit realization, not the practitioner."],
["Stakeholder","An individual affected by a change - ACMP",["If someone’s work, role, behavior, or reward changes, they are a stakeholder.","Stakeholders are defined by impact, not hierarchy."],"Stakeholders are defined by impact, not hierarchy."],
["Sustainability","The ability to maintain the future state - ACMP",["Old behaviors do not return.","Reinforcement is embedded.","Ownership is internal."],"Ownership must be internal for sustainability to exist."],
["Vision","The description of the future state - ACMP",["Vision explains why.","Describes what success looks like.","Inspires alignment."],"Vision explains the “Why” and describes the destination."]
];
function backIcon(){return '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M15 18l-6-6 6-6"/></svg>'}
function helpIcon(){return '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><circle cx="12" cy="12" r="9"/><path d="M9.8 9a2.4 2.4 0 014.6 1c0 2-2.4 2-2.4 4"/><path d="M12 17h.01"/></svg>'}
function arrowIcon(){return '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M5 12h14m-6-6 6 6-6 6"/></svg>'}
function nav(){return '<div class="ct-sb"></div><nav class="ct-nav"><button class="ct-nav-btn" data-action="back" aria-label="Back">'+backIcon()+'</button><p>CORE TERMS &amp; DEFINITIONS</p><button class="ct-nav-btn ct-help" data-action="help" aria-label="Help">'+helpIcon()+'</button></nav>'}
function footer(label){return '<footer class="ct-footer"><button class="ct-cta" data-action="continue"><span>'+label+'</span>'+arrowIcon()+'</button></footer>'}
function intro(){var stats=[["intro-book.svg","20 ESSENTIAL TERMS"],["intro-target.svg","ACMP ALIGNED DEFINITIONS"],["intro-bulb.svg","CCMP EXAM INSIGHTS"]];return '<section class="ct-screen ct-intro">'+nav()+'<div class="ct-intro-content"><p class="ct-badge">LANGUAGE OF CHANGE</p><h1>Core Terms &amp; Definitions.</h1><p class="ct-intro-copy">To master change, you must first master its language. Professional certification exams use precise terminology to set traps. This archive synchronizes your understanding with the ACMP Standard.</p><img class="ct-intro-art" src="'+assetRoot+'intro-illustration.png" alt=""><div class="ct-stats">'+stats.map(function(x){return '<div class="ct-stat"><span><img src="'+assetRoot+'icons/'+x[0]+'" alt=""></span><b>'+x[1]+'</b></div>'}).join("")+'</div><p class="ct-intro-foot"><strong>Build a strong foundation.</strong>Master the language. Pass with confidence.</p></div>'+footer("Enter the Archive")+'</section>'}
function termView(i){var x=terms[i],dense=x[2].length>4?" dense":"",icon="term-"+String(i+1).padStart(2,"0")+".svg";return '<section class="ct-screen'+dense+'">'+nav()+'<div class="ct-term-content"><div class="ct-progress-head"><b>'+String(i+1).padStart(2,"0")+' / 20</b><span>TERMS MASTERED</span></div><div class="ct-progress"><span style="width:'+((i+1)*5)+'%"></span></div><div class="ct-card"><div class="ct-card-head"><p class="ct-kicker">Acquisition Sequence</p><h1>'+x[0]+'.</h1><span class="ct-icon"><img src="'+assetRoot+'icons/'+icon+'" alt=""></span></div><div class="ct-definition">“'+x[1]+'”</div></div><div class="ct-characteristics"><h2>KEY CHARACTERISTICS:</h2><ul>'+x[2].map(function(y){return "<li>"+y+"</li>"}).join("")+'</ul></div><div class="ct-insight"><h2><img src="'+assetRoot+'icons/sparkles.svg" alt="">CCMP INSIGHT</h2><p>'+x[3]+'</p></div></div>'+footer("Next Term")+'</section>'}
function render(){stage.innerHTML=page===0?intro():termView(page-1);bind()}
function bind(){stage.querySelectorAll("[data-action]").forEach(function(el){el.onclick=function(){var a=el.dataset.action;if(a==="back"){if(page>0){page--;render()}else if(history.length>1)history.back();else location.href="lms/curriculum.html"}else if(a==="help")location.href="support/help-support.html?from=core-terms";else if(page<20){page++;render()}else location.href=params.get("next")||"lms/scenario-sorting.html"}})}
var preview=Number(params.get("page"));if(preview>=1&&preview<=21)page=preview-1;render();
})();
