(function(){
"use strict";
var stage=document.getElementById("cu-stage"),page=0,params=new URLSearchParams(location.search);
var modules=[
 {icon:"module-01-information.svg",title:"Introduction to Change Management and CCMP",tag:"Understanding the discipline before applying it",desc:"This module explains why change management enables adoption and business value today, in practice.",points:["What change management is—and why delivery alone fails","How BA, PM, and CM fit together","What CCMP® represents: standard-aligned mastery","Ethics, key skills, and eligibility requirements"],outcome:"Define change management and see what CCMP validates."},
 {icon:"module-02-bookmark.svg",title:"Introduction to ACMP’s Standard",tag:"The authoritative global foundation",desc:"Introduces the ACMP Standard for Change Management as the foundation for professional practice.",points:["Scope and purpose of the ACMP Standard","Core concepts, terms, and definitions","Normative references and anchors","The end-to-end change management process"],outcome:"Understand how the ACMP Standard structures the discipline."},
 {icon:"module-03-search.svg",title:"Evaluating Change Impact and Readiness",tag:"Diagnosis before design",desc:"Building the evidence needed to understand the change, its people impact, and organizational readiness.",points:["Assess change impact across stakeholder groups","Evaluate organizational readiness and capacity","Identify risks, barriers, and dependencies","Translate findings into actionable insight"],outcome:"Diagnose the environment before prescribing action."},
 {icon:"module-04-target.svg",title:"Formulating the Change Strategy",tag:"Context-sensitive design",desc:"Translating diagnosis into strategy by selecting appropriate change approaches.",points:["Select change approaches based on context","Define success measures and outcomes","Align strategy with business objectives","Integrate sponsorship and governance"],outcome:"Strategic thinking over one-size-fits-all solutions."},
 {icon:"module-05-layers.svg",title:"Developing the Change Management Plan",tag:"Turning strategy into coordinated action",desc:"Converting strategic choices into an integrated and measurable change plan.",points:["Plan engagement and communication","Define learning and enablement activities","Coordinate sponsorship and stakeholder actions","Set measurement and reinforcement plans"],outcome:"Create an actionable plan that enables adoption."},
 {icon:"module-06-flash.svg",title:"Executing the Change Plan",tag:"Leading change in motion",desc:"Preparing you to execute and adapt as change unfolds in the real world.",points:["Implement change activities effectively","Monitor adoption and engagement","Respond to resistance and feedback","Adjust strategies while maintaining alignment"],outcome:"Judgment matters more than checklists."},
 {icon:"module-07-checkmark-square.svg",title:"Completing the Change Effort",tag:"Making change stick",desc:"Final focus on sustainment, value realization, and transitions.",points:["Measuring adoption and outcomes","Reinforcing new behaviors","Transitioning ownership to the business","Capturing lessons and closing responsibly"],outcome:"Move beyond implementation to lasting capability."},
 {icon:"module-08-flow-connection.svg",title:"Appendix B – Process Mapping",tag:"Lifecycle alignment",desc:"Clarifying how change work is organized and applied across lifecycle stages.",points:["Relationship between process and subject groups","Aligning activities across the full lifecycle","Logical grouping for consistency","Supporting standards-based practice"],outcome:"Understand the logical organization of change work."},
 {icon:"module-09-security.svg",title:"ACMP Code of Ethics",tag:"Ethical responsibility",desc:"The ethical foundation that governs professional conduct and decision-making.",points:["Purpose and scope of the Code of Ethics","Ethical principles and professional obligations","Responsibilities to individuals and society","The mindset expected of CCMP practitioners"],outcome:"Ethical judgment is inseparable from leadership."},
 {icon:"module-10-medal.svg",title:"Exam Readiness Strategy",tag:"Turning capability into certification",desc:"Bringing the curriculum together into a focused and confident CCMP exam strategy.",points:["Map exam domains to the ACMP Standard","Use scenario-based reasoning","Identify and close readiness gaps","Build a sustainable exam preparation plan"],outcome:"Enter the exam ready to apply, not just recall."}
];
function nav(){return '<div class="cu-sb"></div><nav class="cu-nav"><button class="cu-nav-btn" data-action="back" aria-label="Back"><img src="assets/icons/arrow-left-02.svg" alt=""></button><p>Curriculum Overview</p><button class="cu-nav-btn cu-help" data-action="help" aria-label="Help"><img src="assets/icons/help-circle-24.svg" alt=""></button></nav>'}
function footer(label){return '<footer class="cu-footer"><button class="cu-cta" data-action="continue"><span>'+label+'</span><img src="assets/icons/arrow-right-02.svg" alt=""></button></footer>'}
function intro(){return '<section class="cu-screen cu-intro">'+nav()+'<div class="cu-content"><div><p class="cu-kicker">Introduction</p><h1>The CCMP Learning Journey.</h1></div><div class="cu-callout">Becoming a Certified Change Management Professional (CCMP®) is like mastering the art of guiding people through uncertainty—systematically, ethically, and sustainably.</div><p class="cu-body">The CCMP curriculum is built around the Association of Change Management Professionals (ACMP) Standard for Change Management, which defines change management as a structured, repeatable, and people-centered discipline.</p><p class="cu-body">Rather than focusing on a single methodology, the CCMP curriculum emphasizes principles, professional judgment, and practical application across industries, change types, and organizational contexts.</p><img class="cu-intro-art" src="assets/curriculum/journey-intro.png" alt=""></div>'+footer("Continue")+'</section>'}
function foundation(){var rows=[["Evaluate Impact & Readiness","foundation-search-circle.svg"],["Formulate Strategy","foundation-target.svg"],["Develop Plan","foundation-check-list.svg"],["Execute Plan","foundation-start-up.svg"],["Complete Effort","foundation-checkmark-circle.svg"]];return '<section class="cu-screen cu-foundation">'+nav()+'<div class="cu-content"><div class="cu-head"><p class="cu-kicker">The Core Framework</p><h1>The Foundation:<br>ACMP Standard.</h1></div><div class="cu-process">'+rows.map(function(x,i){return '<div class="cu-process-row"><span><b>0'+(i+1)+'</b>'+x[0]+'</span><span class="cu-process-icon"><img src="assets/curriculum/icons/'+x[1]+'" alt=""></span></div>'}).join("")+'</div><div class="cu-quote">"These process groups form the backbone of both the course structure and the CCMP exam, representing the end-to-end change journey."</div></div>'+footer("Continue")+'</section>'}
function moduleView(i){var x=modules[i];return '<section class="cu-screen cu-module">'+nav()+'<div class="cu-content"><div class="cu-head"><h1>Mastery Sequence.</h1><p>A guided path through the CCMP curriculum</p></div><div class="cu-module-card"><p class="cu-kicker">Module '+String(i+1).padStart(2,"0")+'</p><strong>'+x.title+'</strong><p>'+x.tag+'</p><span class="cu-info"><img src="assets/curriculum/icons/'+x.icon+'" alt=""></span></div><p class="cu-module-desc">'+x.desc+'</p><p class="cu-section-label">In this module, you will explore:</p><div class="cu-points">'+x.points.map(function(p){return '<div class="cu-point">• &nbsp;'+p+'</div>'}).join("")+'</div><div class="cu-outcome"><p class="cu-kicker">Learning Outcome</p><p>'+x.outcome+'</p></div></div>'+footer(i===9?"Continue to Capability Framework":"Continue Journey")+'</section>'}
function finalView(){var caps=["Diagnose complex environments","Design context-sensitive strategies","Enable people to transition","Sustain business outcomes","Apply ethical judgment"];return '<section class="cu-screen cu-final">'+nav()+'<div class="cu-content"><div class="cu-head"><span class="cu-pill cu-kicker">End-State Result</span><h1>Capability Framework</h1></div><div class="cu-capability-quote">"This curriculum does not train you to talk about change. It is a professional capability framework - It prepares you to lead transformation that lasts."</div><p class="cu-section-label">You will be able to:</p><div class="cu-capabilities">'+caps.map(function(x){return '<div class="cu-capability"><span class="cu-check">✓</span>'+x+'</div>'}).join("")+'</div></div>'+footer("Continue")+'</section>'}
function render(){stage.innerHTML=page===0?intro():page===1?foundation():page===12?finalView():moduleView(page-2);bind()}
function bind(){stage.querySelectorAll("[data-action]").forEach(function(el){el.onclick=function(){if(el.dataset.action==="back"){if(page>0){page--;render()}else if(history.length>1)history.back();else location.href="lms/phase-controller.html"}else if(el.dataset.action==="help")location.href="support/help-support.html?from=curriculum";else if(el.dataset.action==="continue"){if(page<12){page++;render()}else location.href=params.get("next")||"lms/core-terms.html"}}})}
var preview=Number(params.get("page"));if(preview>=1&&preview<=13)page=preview-1;render();
})();
