(function(){
"use strict";
var stage=document.getElementById("dm-stage");
var reviewed=[false,false,false,false,false,false,false];
var sheet=-1;
var params=new URLSearchParams(location.search);
var lenses=[
  {name:"Delivery vs. Transition",size:"short",body:['<p>If your Change Definition reads like a project plan — "implement this, deploy that, roll out the other" — it\'s not a change definition yet. A real change definition describes the behavioral, workflow, and decision-making shifts that need to happen, and what sustainment looks like once they do.</p>']},
  {name:"The Change Equation",size:"tall",body:['<p>Think of it this way: Change equals Behavior, plus Workflow, plus Context.</p>','<ul><li>Behavior — what people must do differently.</li><li>Workflow — what processes and handoffs change.</li><li>Context — the KPIs, governance, incentives, and capacity that must support the new way of working.</li></ul>','<p>If context isn\'t defined, adoption becomes fragile.</p>']},
  {name:"The Three-Layer Model",title:"The Three-Layer Definition Model.",size:"tall",body:['<p>Global transformation offices define change in three layers.</p>','<ul><li>The Artifact Layer — systems, policies, structures.</li><li>The Workflow Layer — how work flows and how decisions are made.</li><li>And the Identity Layer — who people must become.</li></ul>','<p>Resistance rarely comes from the artifact. It comes from workflow friction and identity threat.</p>']},
  {name:"Future-State Conditions",title:"Definition by Future-State Conditions.",size:"medium",body:['<p>Define your change using observable statements.</p>','<p>“Decisions are made using X data source.”<br>“Approvals follow Y workflow.”<br>“Workarounds drop below Z threshold.”</p>','<p>This prevents vague definitions like — “be more agile.”</p>']},
  {name:"Change Boundary Discipline",size:"short",body:['<p>Explicitly define what is in scope, what is out of scope, what is non-negotiable, and where design freedoms exist.</p>','<p>Without those boundaries, every stakeholder redefines the change in their favor.</p>']},
  {name:"Interdependency & Change-Load",title:"The Interdependency and Change-Load Lens.",size:"medium",body:['<p>Before finalizing your definition, ask: What else is changing? Where is change fatigue highest? Which groups are already overloaded?</p>','<p>A perfect definition that ignores change load becomes un-executable.</p>']},
  {name:"Assumption Mapping",size:"medium",body:['<p>Surface the hidden assumptions buried in the business case.</p>','<p>“People will trust the new data.”<br>“Managers will enforce compliance.”<br>“Teams will have time to adapt.”</p>','<p>Rewrite these as transition requirements — not hopes.</p>']}
];
function nav(){return '<div class="dm-sb"></div><nav class="dm-nav"><button class="dm-nav-btn" data-action="back" aria-label="Back"><img src="assets/icons/arrow-left-02.svg" alt=""></button><p>Strategic Application</p><button class="dm-nav-btn dm-help" data-action="help" aria-label="Help"><img src="assets/icons/help-circle-24.svg" alt=""></button></nav>'}
function lensIcon(){return '<img src="assets/icons/zoom-in-area-16.svg" alt="">'}
function row(x,i){var done=reviewed[i];return '<button class="dm-row '+(done?'done':'')+'" data-action="open" data-index="'+i+'" aria-label="Open '+x.name+' details"><span class="dm-row-left"><span class="dm-icon">'+lensIcon()+'</span><span class="dm-row-label">'+x.name+'</span></span><span class="dm-row-end"><img src="assets/icons/'+(done?'checkmark-circle-02-16.svg':'arrow-right-01.svg')+'" alt=""></span></button>'}
function footer(){var complete=reviewed.every(Boolean);return '<footer class="dm-footer"><button class="dm-cta" data-action="continue"'+(complete?'':' disabled')+'><span>Continue</span><img src="assets/icons/'+(complete?'arrow-right-02.svg':'lock-sync-02-20.svg')+'" alt=""></button></footer>'}
function sheetView(i){var x=lenses[i];return '<div class="dm-overlay" data-action="dismiss"><section class="dm-sheet '+x.size+'" role="dialog" aria-modal="true" aria-label="'+x.name+'" data-sheet><button class="dm-sheet-close" data-action="close" aria-label="Close"><img src="assets/icons/cancel-01.svg" alt=""></button><div class="dm-sheet-copy"><span class="dm-kicker">Practical Application</span><h2>'+(x.title||x.name+".")+'</h2><div class="dm-sheet-body">'+x.body.join("")+'</div></div><div class="dm-sheet-ref"><img src="assets/icons/information-square-20.svg" alt=""><span>Case Study Reference Active</span></div><button class="dm-got" data-action="got">Got it</button></section></div>'}
function screen(){return '<section class="dm-screen">'+nav()+'<div class="dm-content"><h1>Defining the Change.</h1><p class="dm-lead">There are seven best practice concepts that sharpen definition quality. They are not important for the CCMP Exam, but they can help you with the practical application of this process.</p><div class="dm-list">'+lenses.map(row).join("")+'</div><div class="dm-hint"><img src="assets/icons/tap-05-16.svg" alt="">Tap a lens to open details</div></div>'+footer()+(sheet>=0?sheetView(sheet):"")+'</section>'}
function render(){stage.innerHTML=screen();bind()}
function close(mark){if(sheet<0)return;if(mark)reviewed[sheet]=true;sheet=-1;render()}
function bind(){stage.querySelectorAll("[data-action]").forEach(function(el){el.onclick=function(e){var action=el.dataset.action;if(action==="back"){if(sheet>=0)close(false);else if(history.length>1)history.back();else location.href="lms/reading.html"}else if(action==="help")location.href="support/help-support.html?from=definition-matrix";else if(action==="open"){sheet=Number(el.dataset.index);render()}else if(action==="close")close(false);else if(action==="dismiss"&&e.target===el)close(false);else if(action==="got")close(true);else if(action==="continue"&&reviewed.every(Boolean))location.href=params.get("next")||"lms/phase-controller.html"}})}
var preview=params.get("state");
if(preview==="complete")reviewed=reviewed.map(function(){return true});
if(preview&&preview!=="complete"){var index=lenses.findIndex(function(x){return x.name.toLowerCase().replace(/[^a-z]+/g,"-").replace(/^-|-$/g,"")===preview});if(index>=0)sheet=index}
render();
})();
