(function(){
"use strict";
var stage=document.getElementById("me-stage"),state="intro",cooldown=45,timer=null;
var icon=function(src,cls){return '<img class="'+(cls||"")+'" src="assets/icons/'+src+'" alt="">';};
var mockIcon=function(src,cls){return icon("mock-"+src+".svg","me-icon "+(cls||""));};
var actionIcon=function(src,label){return '<span class="me-action-icon">'+mockIcon(src)+'<span>'+label+'</span></span>';};
var stats=function(){return '<div class="me-stats"><div class="me-stat"><span class="me-stat-icon gray">'+icon("check-list-16.svg")+'</span><small>QUESTIONS</small><strong>180 Qs</strong></div><div class="me-stat"><span class="me-stat-icon orange">'+icon("clock-01-16.svg")+'</span><small>DURATION</small><strong>230 mins</strong></div><div class="me-stat"><span class="me-stat-icon green">'+icon("target-02-16.svg")+'</span><small>PASSING TARGET</small><strong>70%</strong></div></div>';};
var nav=function(back){return '<div class="me-sb"></div><nav class="me-nav"><button class="me-nav-btn" data-action="'+back+'" aria-label="Back">'+icon("arrow-left-02.svg","back")+'</button><p>MOCK EXAM</p><button class="me-nav-btn help" data-action="help" aria-label="Help">'+icon("help-circle-24.svg","help-icon")+'</button></nav>';};
var introBase=function(button){return '<section class="me-screen">'+nav("back-module")+'<div class="me-scroll"><header class="me-intro-head"><span class="me-badge">'+mockIcon("tv-orange")+'DESKTOP REQUIRED</span><h1>Take Your Mock Exam<br>on Desktop</h1><p>Mock exams are best experienced on desktop for a stable, distraction-free environment, full question visibility, and exam integrity.</p></header><img class="me-illus" src="assets/mock-exam/desktop-exam.png" alt="Phone sending a secure exam to desktop">'+stats()+'</div><footer class="me-bnb">'+button+'<p class="me-bnb-note">We’ll email a secure exam link so you can<br>continue on desktop.</p></footer></section>';};
var primary=function(label,action,extra){return '<button class="me-primary" data-action="'+action+'" '+(extra||"")+'>'+label+'</button>';};
var secondary=function(label,action){return '<button class="me-secondary" data-action="'+action+'">'+label+'</button>';};
var sheetIcon=function(kind){if(kind==="success")return '<div class="me-state-icon success">'+mockIcon("checkmark-badge")+'</div>';if(kind==="error")return '<div class="me-state-icon error">'+mockIcon("mail-block")+'</div>';if(kind==="waiting")return '<div class="me-state-icon blue">'+mockIcon("hourglass")+'</div>';if(kind==="progress")return '<div class="me-state-icon blue">'+mockIcon("tv-blue")+'</div>';return '<div class="me-state-icon success">'+mockIcon("checkmark-badge")+'</div>';};
var overlay=function(kind,title,copy,body){return '<div class="me-overlay" aria-hidden="false"><section class="me-sheet"><div class="me-handle"></div><div class="me-sheet-content">'+sheetIcon(kind)+'<div class="me-state-copy"><h2>'+title+'</h2><p>'+copy+'</p></div>'+body+'</div></section></div>';};
var email=function(){return '<div class="me-email">'+mockIcon("mail-orange")+'<span>Sent to: <b>Sarah@gmail.com</b></span></div>';};
function render(){
 clearInterval(timer);
 if(state==="intro"){stage.innerHTML=introBase(primary('Send Desktop Link '+icon("arrow-right-02.svg"),"send"));bind();return;}
 if(state==="sending"){stage.innerHTML=introBase('<button class="me-primary" disabled><i class="me-spinner"></i>Sending link...</button>');bind();timer=setTimeout(function(){go("sent")},1200);return;}
 if(state==="sent"||state==="cooldown"||state==="error"||state==="waiting"||state==="progress"||state==="ready"||state==="certificate"){
   var base=introBase('<button class="me-primary" disabled><i class="me-spinner"></i>Send Desktop Link</button>');
   var ov="";
   if(state==="sent"||state==="cooldown")ov=overlay("success","Desktop link sent","We emailed a secure mock exam link so you can continue on your desktop.",email()+'<div class="me-sheet-actions">'+primary(actionIcon("mail-white","Open Email App"),"open-email")+'<button class="me-link '+(state==="cooldown"?"disabled":"")+'" data-action="resend">'+(state==="cooldown"?"Resend link in <span id=\"me-count\">"+cooldown+"</span>s":"Resend Link")+'</button></div><p class="me-sheet-foot">You can return here after completing the exam</p>');
   if(state==="error")ov=overlay("error","Couldn't send link","We couldn’t send the desktop link to your email.<br>Please check your internet connection and try again.",email()+'<div class="me-sheet-actions">'+primary(actionIcon("mail-white","Try Again"),"send")+secondary("Contact Support","support")+'</div>');
   if(state==="waiting")ov=overlay("waiting","Waiting for Completion","Your mock exam is in progress on desktop.<br>We’ll notify you here as soon as you complete it.",stats()+'<div class="me-sheet-actions">'+primary(icon("reload-20.svg")+" Verify Status","verify-progress")+secondary(actionIcon("mail-blue","Resend Desktop Link"),"resend")+'</div>');
   if(state==="progress")ov=overlay("progress","In Progress on Desktop","You have started the exam on desktop.<br>Please complete it to see your results.",stats()+'<div class="me-sheet-actions">'+primary(icon("reload-20.svg")+" Verify Status","verify-ready")+secondary(actionIcon("mail-blue","Resend Desktop Link"),"resend")+'</div>');
   if(state==="ready")ov=overlay("success","Results Ready!","Great job! You've completed the mock exam. Your results are now available.",stats()+'<div class="me-sheet-actions">'+primary("View Results "+icon("arrow-right-02.svg"),"summary")+"</div>");
   if(state==="certificate")ov=certificateOverlay();
   stage.innerHTML=base+ov;bind();if(state==="cooldown")startCooldown();return;
 }
 if(state==="summary"){stage.innerHTML=summary();bind();return;}
 if(state==="review"||state==="missed"){stage.innerHTML=review();bind();return;}
}
function summary(){
 var domains=[["Change Impact & Readiness",75],["Change Strategy",68],["Change Management Planning",72],["Implementation & Monitoring",58],["Closure & Transition",78],["Ethics & Professional Conduct",80]];
 return '<section class="me-screen">'+nav("back-module")+'<div class="me-scroll me-result"><article class="me-result-card me-congrats"><div class="me-mini-badge">'+mockIcon("checkmark-badge")+'</div><div><h1>Great Job</h1><p>You\'ve completed the CCMP mock exam.<br>Here\'s your performance summary.</p></div></article><article class="me-result-card me-score"><div class="me-score-main"><div class="me-ring"><div class="me-ring-text"><strong>70%</strong><small>Overall Score</small></div></div><p class="me-score-note">You\'ve met the 70%<br>Verification score.</p></div><i class="me-divider"></i><div class="me-boost"><small>READINESS BOOST</small><strong>+10</strong><p>New Readiness score: <b>72%</b></p></div></article><article class="me-result-card me-totals"><div class="me-total ok"><i>'+mockIcon("tick")+'</i><small>CORRECT</small><strong>126</strong><span>70%</span></div><div class="me-total bad"><i>'+mockIcon("cancel")+'</i><small>INCORRECT</small><strong>36</strong><span>20%</span></div><div class="me-total skip"><i>'+mockIcon("minus-circle")+'</i><small>UNATTEMPTED</small><strong>18</strong><span>10%</span></div></article><article class="me-result-card me-domains"><p>DOMAIN PERFORMANCE ANALYSIS</p>'+domains.map(function(d){return '<div class="me-domain '+(d[1]<60?"weak":"")+'"><span>'+d[0]+'</span><div class="me-bar"><i style="width:'+d[1]+'%"></i></div><b>'+d[1]+'%</b></div>'}).join("")+'</article></div><footer class="me-result-actions">'+primary(actionIcon("eye","Detailed Question Review"),"review")+secondary(actionIcon("certificate","View Certificate"),"certificate")+'</footer></section>';
}
var qs=[
 {n:1,domain:"BUSINESS",ok:true,text:"Situation 1: A PMP situational scenario regarding Business context. What is the logical priority for the Project Manager?"},
 {n:2,domain:"PROCESS",ok:false,text:"Situation 2: A PMP situational scenario regarding Business context. What is the logical priority for the Project Manager..."},
 {n:3,domain:"PROCESS",ok:false,text:"Situation 3: A PMP situational scenario regarding Process context. What is the logical priority for the Project Manager..."},
 {n:4,domain:"PROCESS",ok:true,text:"Situation 4: A PMP situational scenario regarding Business context. What is the logical priority for the Project Manager..."}
];
function question(q,i){var open=i===0;return '<article class="me-question '+(open?"":"collapsed")+'" data-question="'+q.n+'"><div class="me-qhead"><i class="me-qstatus '+(q.ok?"ok":"bad")+'">'+mockIcon(q.ok?"tick":"cancel")+'</i><strong>QUESTION '+q.n+'</strong><span class="me-tag '+(q.ok?"":"bad")+'">'+q.domain+'</span><button class="me-chevron" data-action="toggle-question" aria-label="Toggle question">'+mockIcon("chevron-down")+'</button></div><h3>'+q.text+'</h3><div class="me-options"><div class="me-option correct-choice"><i class="radio"></i><span>A.</span><span>Initial Decision<br>Logic Trace</span><em>Correct '+mockIcon("tick-small")+'</em></div>'+(state==="missed"?'<div class="me-option wrong-choice"><i class="radio"></i><span>B.</span><span>Secondary Action<br>Response</span><em>Selected '+mockIcon("cancel")+'</em></div>':'')+'<div class="me-option"><i class="radio"></i><span>C.</span><span>Baseline Update Request</span></div><div class="me-option"><i class="radio"></i><span>D.</span><span>Stakeholder Escalation</span></div></div><div class="me-explanation"><b>'+mockIcon("book-open")+'Explanation</b><p>In this specific situational trace for Business, PMP logic dictates that impact assessment and stakeholder alignment must occur before updating baselines or initiating remediation.</p></div></article>';}
function review(){return '<section class="me-review-screen">'+nav("summary")+'<div class="me-review-top"><div class="me-domain-tabs"><button class="active">ALL DOMAINS</button><button>PEOPLE</button><button>PROCESS</button><button>BUSINESS</button></div></div><div class="me-review-sheet"><div class="me-filters"><button class="'+(state==="review"?"active":"")+'" data-action="review">ALL QUESTIONS</button><button class="missed '+(state==="missed"?"active":"")+'" data-action="missed">MISSED (12)</button><button class="correct">CORRECT (36)</button></div>'+qs.map(question).join("")+'</div></section>';}
function certificateOverlay(){return '<div class="me-overlay" aria-hidden="false"><section class="me-sheet me-cert-sheet"><div class="me-handle"></div><div class="me-sheet-content"><div class="me-state-icon success">'+mockIcon("checkmark-badge")+'</div><div class="me-state-copy"><h2>Congratulations!</h2><p>You\'ve completed the CCMP mock exam.<br>Here\'s your performance summary.</p></div><div class="me-cert"><div class="me-cert-brand">CertSprints</div><small>OFFICIAL CERTIFICATE OF COMPLETION</small><h2>Ifeoluwa Emmanuel</h2><div class="me-cert-line"></div><p>Has successfully satisfied the requirements of the<br><b>PROJECT MANAGEMENT PROFESSIONAL (PMP)</b><br>certification course through demonstrated competency and evaluation.</p><div class="me-cert-meta"><span>DIRECTOR OF EDUCATION<br>CertSprints</span><span>VERIFICATION DATE<br>FEB 27, 2026</span></div></div><div class="me-info">'+mockIcon("info")+'<div><h3>About this certificate</h3><p>This certificate validates your completion of the CCMP mock exam. It is not an official ACMP Certification</p></div></div></div><footer class="me-cert-actions">'+primary(actionIcon("download","Download Certificate"),"download")+secondary(actionIcon("share","Share Certificate"),"share")+'</footer></section></div>';}
function go(next){state=next;history.replaceState(null,"","?state="+next);render()}
function startCooldown(){cooldown=45;timer=setInterval(function(){cooldown--;var e=document.getElementById("me-count");if(e)e.textContent=cooldown;if(cooldown<=0){clearInterval(timer);go("sent")}},1000)}
function bind(){stage.querySelectorAll("[data-action]").forEach(function(el){el.onclick=function(){var a=el.dataset.action;if(a==="back-module")location.href="lms/module-quiz.html";else if(a==="help")location.href="support/help-support.html?from=mock-exam";else if(a==="send")go("sending");else if(a==="open-email")go("waiting");else if(a==="resend"&&state!=="cooldown")go("cooldown");else if(a==="support")location.href="support/help-support.html?from=mock-exam";else if(a==="verify-progress")go("progress");else if(a==="verify-ready")go("ready");else if(a==="summary")go("summary");else if(a==="review")go("review");else if(a==="missed")go("missed");else if(a==="certificate")go("certificate");else if(a==="toggle-question")el.closest(".me-question").classList.toggle("collapsed");else if(a==="download")go("certificate");else if(a==="share")location.href="lms/capability-matrix.html";}})}
var requested=new URLSearchParams(location.search).get("state");if(requested)state=requested;render();
})();
