/** Figma 4441:60481–4452:62028 — Sprint Feed content */
window.NOTIFICATION_DATA = {
  tabs: [
    { id: "everything", label: "Everything" },
    { id: "priority", label: "Priority" },
    { id: "insights", label: "Insights" },
  ],
  items: [
    {
      id: "exam-date",
      categories: ["everything", "priority"],
      icon: "notification-03.svg",
      iconBg: "#fff1f2",
      title: "Rethink your exam date",
      body: "Current sprint speed suggests March 24 may be too soon.",
      time: "2d ago",
      unread: true,
    },
    {
      id: "recall-dip",
      categories: ["everything", "insights"],
      icon: "ai-brain.svg",
      iconBg: "#e6f2ff",
      title: "Recall mastery dipped",
      body: "Agile topics recall dropped 18% over the last two sprints",
      time: "2d ago",
      unread: true,
    },
    {
      id: "people-domain",
      categories: ["everything", "insights"],
      icon: "fire.svg",
      iconBg: "#fff0eb",
      title: "People domain need attention",
      body: "You've skipped 8 People domain topics. This is your biggest risk area.",
      time: "4d ago",
      unread: false,
    },
    {
      id: "great-progress",
      categories: ["everything"],
      icon: "checkmark-circle.svg",
      iconBg: "#f0fdf4",
      title: "Great progress!",
      body: "You closed the gap in process domain by 12%",
      time: "4d ago",
      unread: false,
    },
  ],
};
