/** Figma 4441:60481–4452:62028 — Sprint Feed content */
window.NOTIFICATION_DATA = {
  tabs: [
    { id: "everything", label: "Everything" },
    { id: "priority", label: "Priority" },
    { id: "insights", label: "Insights" },
  ],
  items: [
    {
      id: "exam-date",
      categories: ["everything", "priority"],
      icon: "notification-03.svg",
      iconBg: "#fff1f2",
      title: "Rethink your exam date",
      body: "Current sprint speed suggests March 24 may be too soon.",
      time: "2d ago",
      unread: true,
    },
    {
      id: "recall-dip",
      categories: ["everything", "insights"],
      icon: "ai-brain.svg",
      iconBg: "#e6f2ff",
      title: "Recall mastery dipped",
      body: "Agile topics recall dropped 18% over the last two sprints",
      time: "2d ago",
      unread: true,
    },
    {
      id: "people-domain",
      categories: ["everything", "insights"],
      icon: "fire.svg",
      iconBg: "#fff0eb",
      title: "People domain need attention",
      body: "You've skipped 8 People domain topics. This is your biggest risk area.",
      time: "4d ago",
      unread: false,
    },
    {
      id: "great-progress",
      categories: ["everything"],
      icon: "checkmark-circle.svg",
      iconBg: "#f0fdf4",
      title: "Great progress!",
      body: "You closed the gap in process domain by 12%",
      time: "4d ago",
      unread: false,
    },
  ],
  settings: [
    {
      id: "priority-alerts",
      icon: "security-check.svg",
      iconBg: "#fff1f2",
      title: "Priority Alerts",
      body: "Clinical risks and exam date warnings",
      enabled: true,
    },
    {
      id: "recall-insights",
      icon: "ai-brain.svg",
      iconBg: "#e6f2ff",
      title: "Recall Insights",
      body: "Logical dips and mastery skills",
      enabled: true,
    },
    {
      id: "streak-protection",
      icon: "fire.svg",
      iconBg: "#fff0eb",
      title: "Streak Protection",
      body: "Cutoff warnings and rituals",
      enabled: true,
    },
    {
      id: "cohort-protection",
      icon: "user-multiple.svg",
      iconBg: "#f1f5f9",
      iconBgOn: "#e6f2ff",
      title: "Cohort Protection",
      body: "Community progress and buddy pings",
      enabled: false,
    },
  ],
  focus: {
    hour: 9,
    minute: 0,
    period: "AM",
    label: "9:00 AM",
  },
};
